@startuml Complete MetaMeta Graph (Styled)
skinparam nodesep 15
skinparam ranksep 20

' Define all nodes with:
' - Background color based on their type (pale colors)
' - Border style based on their metaLevel
' - Relation nodes have bold colored text (not filled background)

' Nodes from types.sheet
' class: type=metaType, metaLevel=ml2
rectangle "class" as class #FFFFCC

' metaType: type=metaNType, metaLevel=ml3 (TYPE NODE - bold cursive colored text)
hexagon "<b><i><color:#000000>mt</color></i></b>" as metaType #E6F0FF

' metaLevelType: type=metaNType, metaLevel=ml3 (TYPE NODE - bold cursive colored text)
hexagon "<b><i><color:#000000>mlt</color></i></b>" as metaLevelType #E6F0FF

' metaRelation: type=metaNType, metaLevel=ml3
rectangle "mr" as metaRelation #E6F0FF

' metaRelationSignature: type=metaNType, metaLevel=ml3
rectangle "mrs" as metaRelationSignature #E6F0FF

' metaNType: type=metaNType, metaLevel=mlN (TYPE NODE - bold cursive colored text)
(<b><i><color:#000000>mnt</color></i></b>) as metaNType #E6F0FF

' Nodes from metaLevels.sheet
' All have type=metaLevelType, metaLevel=ml2
rectangle "ml0" as ml0 #E6FFE6
rectangle "ml1" as ml1 #E6FFE6
hexagon "ml2" as ml2 #E6FFE6
(ml3) as ml3 #E6FFE6
(mlN) as mlN #E6FFE6

' Nodes from metaRelations.sheet (relation type nodes)
' All have type=metaNType, metaLevel=ml3
' Bold text with relation color, background=metaNType color (very light blue)
rectangle "<b><color:#000000>type</color></b>" as type_rel #E6F0FF
rectangle "<b><color:#000000>ml</color></b>" as metaLevel_rel #E6F0FF
rectangle "<b><color:#FF8800>sig</color></b>" as signature_rel #E6F0FF
hexagon "<b><color:#0000FF>st</color></b>" as sourceType_rel #E6F0FF
hexagon "<b><color:#AA00FF>tt</color></b>" as targetType_rel #E6F0FF
(<b><color:#00AA00>nml</color></b>) as nextMetaLevel_rel #E6F0FF

' Nodes from metaRelationSignatures.sheet (all private)
' All have type=metaNType, metaLevel=ml3
(a2at) as sig1 #E6F0FF
(a2mlt) as sig2 #E6F0FF
(mnt2mnt) as sig3 #E6F0FF
(ml2ml) as sig4 #E6F0FF
(mr2mrs) as sig5 #E6F0FF
(mrs2mt) as sig6 #E6F0FF

' Relations - EXCLUDING type and metaLevel relations
' Only showing: signature, sourceType, targetType, nextMetaLevel

' -nextMetaLevel-> relations (green)
ml0 -[#00AA00]-> ml1
ml1 -[#00AA00]-> ml2
ml2 -[#00AA00]-> ml3
ml3 -[#00AA00]-> mlN
mlN -[#00AA00]-> mlN

' -signature-> relations (orange)
type_rel -[#FF8800]-> sig1
metaLevel_rel -[#FF8800]-> sig2
signature_rel -[#FF8800]-> sig3
signature_rel -[#FF8800]-> sig5
nextMetaLevel_rel -[#FF8800]-> sig4
sourceType_rel -[#FF8800]-> sig3
sourceType_rel -[#FF8800]-> sig6
targetType_rel -[#FF8800]-> sig3
targetType_rel -[#FF8800]-> sig6

' -targetType-> relations (purple)
sig1 -[#AA00FF]-> class
sig1 -[#AA00FF]-> metaType
sig1 -[#AA00FF]-> metaNType
sig1 -[#AA00FF]-> metaLevelType
sig2 -[#AA00FF]-> metaLevelType
sig3 -[#AA00FF]-> metaNType
sig4 -[#AA00FF]-> metaLevelType
sig5 -[#AA00FF]-> metaRelationSignature
sig6 -[#AA00FF]-> metaType

' -sourceType-> relations (blue)
sig3 -[#0000FF]-> metaNType
sig4 -[#0000FF]-> metaLevelType
sig5 -[#0000FF]-> metaRelation
sig6 -[#0000FF]-> metaRelationSignature

' Legend
legend right
  |= Shape |= Visibility |
  | Rectangle | public |
  | Hexagon | public+1 |
  | Circle | private |
  ====
  |= Type Node |= Background Color |
  | <b><i><color:#0066CC>mnt</color></i></b> (metaNType) | <back:#E6F0FF>Very Light Blue</back> |
  | <b><i><color:#CC9900>mt</color></i></b> (metaType) | <back:#FFFFCC>Pale Yellow</back> |
  | <b><i><color:#00AA00>mlt</color></i></b> (metaLevelType) | <back:#E6FFE6>Pale Green</back> |
  ====
  |= Edge Color |= Relation Type |
  | <color:#FF8800>Orange</color> | signature |
  | <color:#0000FF>Blue</color> | sourceType |
  | <color:#AA00FF>Purple</color> | targetType |
  | <color:#00AA00>Green</color> | nextMetaLevel |
  ====
  |= Relations |
  | <b><color:#000000>type</color></b> | type |
  | <b><color:#000000>ml</color></b> | metaLevel |
  | <b><color:#FF8800>sig</color></b> | signature |
  | <b><color:#0000FF>st</color></b> | sourceType |
  | <b><color:#AA00FF>tt</color></b> | targetType |
  | <b><color:#00AA00>nml</color></b> | nextMetaLevel |
  ====
  |= Abbreviation |= Full Name |
  | mt | metaType |
  | mlt | metaLevelType |
  | mr | metaRelation |
  | mrs | metaRelationSignature |
  | mnt | metaNType |
  | a2at | any-to-anyType |
  | a2mlt | any-to-metaLevelType |
  | mnt2mnt | metaNType-to-metaNType |
  | ml2ml | metaLevel-to-metaLevel |
  | mr2mrs | metaRelation-to-metaRelationSignature |
  | mrs2mt | metaRelationSignature-to-metaType |
endlegend

@enduml
